title: Survey-Enhance documentation
author: Nikhil Woodruff
copyright: "2022"

execute:
  execute_notebooks: "cache"

repository:
  url: https://github.com/nikhilwoodruff/survey-enhance
  branch: master
  path_to_book: docs

bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: furo
    pygments_style: default
    
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinxarg.ext"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.napoleon"
    - "sphinx_math_dollar"
    - "sphinx.ext.mathjax"
    - "sphinxcontrib.bibtex"
